# Generated by Django 3.0.8 on 2020-08-02 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('testsuits', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testsuites',
            new_name='Testsuits',
        ),
    ]
