# Generated by Django 3.0.8 on 2020-08-02 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsuits', '0002_auto_20200802_2251'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testsuits',
            table='tb_testsuits',
        ),
    ]
